version: "3"
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12
    volumes:
      - ../..:/workspaces:cached
      - pgadmin-data:/var/lib/pgadmin
    command: sleep infinity
    # https://goledger.medium.com/reaching-hosts-localhost-from-inside-a-vscode-devcontainer-932e1c08df5c
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: s140217@ap.be
      PGADMIN_DEFAULT_PASSWORD: Newpassword
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Newpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  pgadmin-data:
  postgres-data:
